
autoload -U zrecompile
cd ${ZDOTDIR:-$HOME}

zrecompile -p .zshrc
zrecompile -p .zshenv
zrecompile -p .zlogout
zrecompile -p .zlogin
zrecompile -p .zcompdump
rm -f *.old(.N)

for f in $ZDOTDIR/functions.d/^(*.zwc)(.); do
	zrecompile -p $f
	rm -f $f.zwc.old
done

for f in $ZDOTDIR/plugins/**/*.zsh; do
	zrecompile -p $f
	rm -f $f.zwc.old
done


